### ISSUE TITLE
hotwater_realt, heat_realt가 entity에 등록이 안 되어 있네요.

### ISSUE THREAD

**Issue by kkpg** [harwin1/ha-addons#15]
안녕하세요.

아래와 같은 로그와 나와서 확인해 보니
------------------------------
Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:270
integration: MQTT (documentation, issues)
First occurred: March 22, 2024 at 11:20:39 PM (15 occurrences)
Last logged: March 22, 2024 at 11:38:20 PM

Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/bestin_wallpad/bestin_hotwater_realt_consumption/config', message: '{'_intg': 'sensor', 'name': 'bestin_hotwater_realt_consumption', 'state_topic': 'bestin/energy/hotwater/realt/state', 'unit_of_measurement': 'm', 'device_class': '³', 'value_template': '/', 'unique_id': 'bestin_hotwater_realt_consumption', 'device': {'identifiers': ['bestin_wallpad'], 'name': 'bestin_wallpad', 'manufacturer': 'HDC BESTIN', 'model': 'Bestin Wallpad', 'sw_version': 'lunDreame/ha-addons/bestin_wallpad'}, 'platform': 'mqtt'}'
Error 'expected SensorDeviceClass or one of 'date', 'enum', 'timestamp', 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'volume_flow_rate', 'water', 'weight', 'wind_speed' for dictionary value @ data['device_class']' when processing MQTT discovery message topic: 'homeassistant/sensor/bestin_wallpad/bestin_heat_realt_consumption/config', message: '{'_intg': 'sensor', 'name': 'bestin_heat_realt_consumption', 'state_topic': 'bestin/energy/heat/realt/state', 'unit_of_measurement': 'm', 'device_class': '³', 'value_template': '/', 'unique_id': 'bestin_heat_realt_consumption', 'device': {'identifiers': ['bestin_wallpad'], 'name': 'bestin_wallpad', 'manufacturer': 'HDC BESTIN', 'model': 'Bestin Wallpad', 'sw_version': 'lunDreame/ha-addons/bestin_wallpad'}, 'platform': 'mqtt'}'
-------------------------------------

bestin_hotwater_realt_consumption, bestin_heat_realt_consumption
이 두 entity가 등록이 안 되어 있더라구요.

const.js에서 hotwater_realt, heat_realt를 아래와 같이 수정하니 되네요. ㅎ
수정되면 좋을 것 같습니다.

----------------------------------------
const HEMSUNIT = {
    "electric_total": ["kWh", "energy", "{{ (value | float / 100) }}"],
    "electric_realt": ["W", "power"],
    "water_total": ["m³", "water", "{{ (value | float / 1000) | round(2) }}"],
    "water_realt": [["m³/h", ""], ["m³/h", "{{ (value | float / 1000) }}"]],
    "hotwater_total": ["m³", "", "{{ (value | float / 1000) | round(2) }}"],
    "hotwater_realt": [["m³/h", ""], ["m³/h", "{{ (value | float / 1000) }}"]],
    "gas_total": ["m³", "gas", "{{ (value | float / 1000) | round(2) }}"],
    "gas_realt": [["m³/h", ""], ["m³/h", "{{ (value | float / 10) }}"]],
    "heat_total": ["m³", "", "{{ (value | float / 1000) | round(2) }}"],
    "heat_realt": [["m³/h", ""], ["m³/h", "{{ (value | float / 1000) }}"]]
---------------------------------

감사합니다.

**Comment by lunDreame** [comment]
Main 브랜치에 Pr남겨 주시면 확인후 승인 하겠습니다~
